"""默认配置:股票池、因子窗口、成本与资金默认值。"""

DEFAULT_UNIVERSE = [
    "AAPL.US", "MSFT.US", "NVDA.US", "GOOGL.US", "AMZN.US",
    "META.US", "TSLA.US", "JPM.US", "V.US", "UNH.US",
]

DEFAULT_TOP_N = 5
MOMENTUM_LOOKBACK = 126
MOMENTUM_SKIP = 21
VOL_WINDOW = 63

DEFAULT_COMMISSION = 0.0
DEFAULT_SLIPPAGE = 0.0005
DEFAULT_CAPITAL = 1_000_000

DATA_DIR = "data"
